### PR TITLE
It seems like these request counters should be incremented?

### PR DESCRIPTION
**Pull request by jla415**
Correct me if I'm wrong here... Thanks

### CODE REVIEW

**Comment by pocesar** [comment]
nope, not really. the currentId should only change when the commands are changed. it's used to keep track of the current request

**Comment by jla415** [comment]
Maybe i'm missing something but it reuses id 1 for both subscribe and authorize right now?

**Comment by jla415** [comment]
```javascript
client.connect(8080, 'localhost').then(function(socket){
    socket.stratumSubscribe('NodeMiner');
    socket.stratumAuthorize('user','pass');
});
```

^^^ this code reuses id 1 for the authorize request and the pending subscription request is lost

**Comment by pocesar** [comment]
every time there's a call to `stratumSend`, the id gets incremented. both `stratumSubscribe` and `stratumAuthorize` calls `stratumSend`, that's why.  but since you are calling them in sucession, they are executing in the same id since they are in the same even loop, so it should be:

```js
client.connect(8080, 'localhost').then(function(socket){
    socket.stratumSubscribe('NodeMiner').then(function() {
      socket.stratumAuthorize('user','pass');
    });
});
```

**Comment by jla415** [comment]
in stratumSend you are only incrementing the counter if data.id is not set, which you are setting in stratumSubscribe, stratumAuthorize and stratumSubmit.

https://github.com/pocesar/node-stratum/blob/c4decc5be6c66173eac7a5ce76de576c9e9a184c/src/client.ts#L320

I did try waiting for the subscribe promise to resolve before digging into the code and discovering that the ids were not being incremented

**Comment by pocesar** [comment]
my bad, the code I wrote is wrong and the README is also wrong (for the client part). you should only call those on the `mining` event like so:

```js
client.on('mining', function(req, socket, type, name) {
  // this is an answer from the server
  switch (name) {
    case 'subscribe':
      client.stratumAuthorize('user', 'pass');
      break;
    case 'authorize': 
      // do more stuff
      break;
  }
})

client.connect(8080, 'localhost').then(function(socket){
  socket.stratumSubscribe('NodeMiner')
})
```

since I'm rewriting this library, I'll also add some docs and better examples, and make the API more intuitive

**Comment by jla415** [comment]
This works kind of works, but you are still reusing the request id as 1 in the authorize request and when the second response comes back with the same id it is not correctly recognized

from pool.on('mining.error'):  Error: No suitable command was issued from the server
pool.on('mining'): {"id":1,"error":null,"result":true} "result" undefined


I get what you are trying to do but the request id does need to be incremented somewhere and it is not currently doing it

**Comment by pocesar** [comment]
indeed, and there's also a bug because of this line https://github.com/pocesar/node-stratum/blob/master/src/client.ts#L145

the pending ID gets deleted, and when a new command is issued, the ID still exists (because event emitting is actually synchronous), and when the socket.stratumAuthorize is called, this.currentId is still the old one, so yes, your patch is correct, I apologize

**Comment by jla415** [comment]
gonna close this since i'm adding other stuff to my fork and don't want to pollute your rewrite...  thanks

**Pull request closed without merging**
